version: "2.1"
volumes: 
  data: {}
services:
  db: 
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123123"
      MYSQL_DATABASE: "flaskapp"
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes: 
      - data:/var/lib/mysql
      - ./basic-db.sql:/docker-entrypoint-initdb.d/init.sql