---
- name: ec2 launcher
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    region: us-east-1
    security_group: default_sg_webserver
    keypair: amaro-dev
  tasks:
  - name: Create a security group
    ec2_group:
      name: "{{ security_group }}"
      description: The webservers security group
      region: "{{ region }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0
    register: security_group
  - name: Launching ec2
    ec2: 
      instance_type: t3.micro
      key_name: "{{ keypair }}"
      image: ami-0cfee17793b08a293
      region: "{{ region }}"
      group_id: "{{ security_group.group_id }}"
      count: 1
      vpc_subnet_id: subnet-4a2cc32d
      wait: yes
      assign_public_ip: yes
      instance_tags: 
          Name: ansible-ec2
    register: ec2
  - name: create RDS instance
    rds:
      command: create
      region: "{{ region }}"
      instance_name: RDS-webserver
      db_engine: MySQL
      size: 20
      instance_type: db.t2.micro
      username: mysql_admin
      password: 1nsecure
      tags:
        Environment: testing
        Application: webserver
  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_ip }}"
      port: 22 
      state: started
    with_items: "{{ ec2.instances }}"
  - name: Add the newly created host so that we can further contact it
    add_host:
      name: "{{ item.public_ip }}"
      groups: webservers
    with_items: "{{ ec2.instances }}"